version: "3.7"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./public:/var/www/laravel/public
    networks:
      - sampleapp_net
    depends_on:
      - phpfpm
  phpfpm:
    image: juve534/php-fpm:7.3
    volumes:
      - ./:/var/www/html
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - sampleapp_net
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=homestead
      - DB_USERNAME=root
      - DB_PASSWORD=pass
      - PHP_IDE_CONFIG=serverName=phpfpm
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=homestead
    networks:
      - sampleapp_net

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - sampleapp_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - sampleapp_net

  # ElasticMQ
  elasticmq:
    image: softwaremill/elasticmq
    volumes:
      - ./docker/elasticmq/custom.conf://opt/elasticmq.conf:ro
    networks:
      - sampleapp_net

  queue-worker:
    image: juve534/php-fpm:7.3
    volumes:
      - ./:/var/www/html
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - sampleapp_net
    depends_on:
      - mysql
      - elasticmq
    command: ["php", "artisan", "queue:work"]
    restart: always

networks:
  sampleapp_net:
    driver: bridge
